name: allervie-analytics
region: nyc
services:
  - name: web
    dockerfile_path: Dockerfile
    github:
      repo: jhillbht/allervie-analytics-oauth-flow
      branch: main
      deploy_on_push: true
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xs
    envs:
      - key: DEBUG
        value: "False"
        scope: RUN_TIME
        type: GENERAL
      - key: FLASK_SECRET_KEY
        value: "1a2b3c4d5e6f7g8h9i0j"
        scope: RUN_TIME
        type: SECRET
      - key: GOOGLE_CLIENT_ID
        value: "22083613754-d1omeg2958vrsndpqg2v1jp0ncm7sr23.apps.googleusercontent.com"
        scope: RUN_TIME
        type: SECRET
      - key: GOOGLE_CLIENT_SECRET
        value: "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"
        scope: RUN_TIME
        type: SECRET
      - key: REDIRECT_URI
        value: "https://allervie-analytics-wzspj.ondigitalocean.app/auth/callback"
        scope: RUN_TIME
        type: GENERAL
      - key: GA4_PROPERTY_ID
        value: "399455767"
        scope: RUN_TIME
        type: SECRET
      - key: GOOGLE_ADS_CUSTOMER_ID
        value: "8437927403"
        scope: RUN_TIME
        type: SECRET
      - key: GOOGLE_ADS_DEVELOPER_TOKEN
        value: "HpV1ZGZOKj6JewVzrOdXXw"
        scope: RUN_TIME
        type: SECRET